config/routes.rb
ClassPortal::Application.routes.draw do
  resources :messages
  resources :user_histories
  resources :grades
  resources :admins
  resources :courses, :collection => {:requestEnrollment => :post}

  
  root 'static_pages#home'
  get 'sessions/new'
  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/instructor"
  get "static_pages/student"
  get "students/new"
  get "admins/new"
  get "super_admins/new"
  get "courses/new"
  get "courses/view"
  get "courses/edit"
  get 'viewCourse' => 'courses#view'
  
  
  
  
  
  
  get "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  post "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  
  
  get 'searchCourse' => 'courses#searchCourse'
  
  get 'editCourse' => 'courses#edit'
  get 'enrollCourse/:id/enroll' => 'courses#enroll'
  post 'enrollCourse/:id/enroll' => 'courses#enroll'
 
  get "student_courses/viewHistory"
  get '/viewHistory/:id' => 'student_courses#viewHistory'
  post '/viewHistory/:id' => 'student_courses#viewHistory'
  
 
  get "students/view"
  get 'viewStudent' => 'students#view' 
 
  resources :courses do
  member do
    get 'enroll'
  end
end
  get 'addInst' =>'users#newInstructor'
  post 'createInstructor' =>'users#createInstructor'
  get 'editInst' => 'instructors#edit'
  get 'signup'  => 'students#new'
  get 'edit' => 'users#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/courses/:course_id/grades" => 'student_courses#grades'
  get "/courses/:course_id/requestEnrollment" => 'courses#requestEnrollment'
  get "/grades/new" => "student_courses#newGrade"
  post "/grades/new" => "student_courses#createGrade"
  
  get "/enrollmentRequests" => "student_courses#showEnrollmentRequests"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/approve" => "student_courses#approveRequest"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/deny" => "student_courses#denyRequest"

  
  get "/courses/:course_id/students" => "courses#students"
  get "/student_courses/:student_course_id/edit" => "grades#edit"
  
  get "/users/:user_id/history" => "user_histories#for_user"
  get "/courses/:course_id/drop" => "courses#dropStudent"
  get "/courses/:course_id/students/:student_id/drop" => "courses#drop"
  get "/courses/:course_id/requestInactive" => "courses#requestInactive"

  resources :users
  resources :students
  resources :instructors
  resources :super_admins
  resources :student_courses

  

end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
end

app/controllers/user_histories_controller.rb
class UserHistoriesController < ApplicationController
  before_action :set_user_history, only: [:show, :edit, :update, :destroy]

  # GET /user_histories
  # GET /user_histories.json
  def index
    @user_histories = UserHistory.all
    @user_histories_all = true
  end

  # GET /user_histories/1
  # GET /user_histories/1.json
  def show
  end

  # GET /user_histories/new
  def new
    @user_history = UserHistory.new
  end

  # GET /user_histories/1/edit
  def edit
  end

  # POST /user_histories
  # POST /user_histories.json
  def create
    @user_history = UserHistory.new(user_history_params)

    respond_to do |format|
      if @user_history.save
        format.html { redirect_to @user_history, notice: 'User history was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_history }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_histories/1
  # PATCH/PUT /user_histories/1.json
  def update
    respond_to do |format|
      if @user_history.update(user_history_params)
        format.html { redirect_to @user_history, notice: 'User history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_histories/1
  # DELETE /user_histories/1.json
  def destroy
    @user_history.destroy
    respond_to do |format|
      format.html { redirect_to user_histories_url }
      format.json { head :no_content }
    end
  end
  
  def for_user
    @user_histories = UserHistory.where("user_id = ?", params[:user_id])
    @user_histories_all = false
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_history
      @user_history = UserHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_history_params
      params.require(:user_history).permit(:user_id, :course_id, :action)
    end
end

app/helpers/user_histories_helper.rb
module UserHistoriesHelper
end

app/views/user_histories/_form.html.erb
<%= form_for(@user_history) do |f| %>
  <% if @user_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_history.errors.count, "error") %> prohibited this user_history from being saved:</h2>

      <ul>
      <% @user_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_histories/edit.html.erb
<h1>Editing User History</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_history %> |
<%= link_to 'Back', user_histories_path %>

app/views/user_histories/index.html.erb
<p id="notice"><%= notice %></p>

<% if @user_histories_all %>
  <h1>All Course History Entries</h1>
<% else %>
  <h1>Your Course History</h1>
<% end %>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <% if @user_histories_all %>
          <th>Student</th>
        <% end %>
        <th>Course</th>
        <th>Action</th>
        <th>Timestamp</th>
      </tr>
    </thead>

  <tbody>
    <% @user_histories.reverse.each do |user_history| %>
      <tr>
        <% if @user_histories_all %>
          <% student = Student.find(user_history.user_id) %>
          
          <% if !student.nil? %>
            <td><%= link_to student.name, student %></td>
          <% else %>
            <td><%= user_history.user_id %></td>
          <% end %>
        <% end %>
        
        <% course = Course.find(user_history.course_id) %>
        <% if !course.nil? %>
          <td><%= link_to course.title, course %></td>
        <% else %>
          <td><%= user_history.course_id %></td>
        <% end %>
        <td><%= user_history.action %></td>
        <td><%= user_history.created_at %></td>
        <!--<td><%= link_to 'Show', user_history %></td>-->
        <!--<td><%= link_to 'Edit', edit_user_history_path(user_history) %></td>-->
        <!--<td><%= link_to 'Destroy', user_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New User history', new_user_history_path %>-->

app/views/user_histories/new.html.erb
<h1>New User History</h1>

<%= render 'form' %>

<%= link_to 'Back', user_histories_path %>

app/views/user_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_history.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @user_history.course_id %>
</p>

<p>
  <strong>Action:</strong>
  <%= @user_history.action %>
</p>

<%= link_to 'Edit', edit_user_history_path(@user_history) %> |
<%= link_to 'Back', user_histories_path %>