config/routes.rb
ClassPortal::Application.routes.draw do
  resources :messages
  resources :user_histories
  resources :grades
  resources :admins
  resources :courses, :collection => {:requestEnrollment => :post}

  
  root 'static_pages#home'
  get 'sessions/new'
  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/instructor"
  get "static_pages/student"
  get "students/new"
  get "admins/new"
  get "super_admins/new"
  get "courses/new"
  get "courses/view"
  get "courses/edit"
  get 'viewCourse' => 'courses#view'
  
  
  
  
  
  
  get "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  post "/viewSelectCourse/:title/:number" => "courses#viewSelectCourse"
  
  
  get 'searchCourse' => 'courses#searchCourse'
  
  get 'editCourse' => 'courses#edit'
  get 'enrollCourse/:id/enroll' => 'courses#enroll'
  post 'enrollCourse/:id/enroll' => 'courses#enroll'
 
  get "student_courses/viewHistory"
  get '/viewHistory/:id' => 'student_courses#viewHistory'
  post '/viewHistory/:id' => 'student_courses#viewHistory'
  
 
  get "students/view"
  get 'viewStudent' => 'students#view' 
 
  resources :courses do
  member do
    get 'enroll'
  end
end
  get 'addInst' =>'users#newInstructor'
  post 'createInstructor' =>'users#createInstructor'
  get 'editInst' => 'instructors#edit'
  get 'signup'  => 'students#new'
  get 'edit' => 'users#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/courses/:course_id/grades" => 'student_courses#grades'
  get "/courses/:course_id/requestEnrollment" => 'courses#requestEnrollment'
  get "/grades/new" => "student_courses#newGrade"
  post "/grades/new" => "student_courses#createGrade"
  
  get "/enrollmentRequests" => "student_courses#showEnrollmentRequests"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/approve" => "student_courses#approveRequest"
  get "/enrollmentRequests/courses/:course_id/students/:student_id/deny" => "student_courses#denyRequest"

  
  get "/courses/:course_id/students" => "courses#students"
  get "/student_courses/:student_course_id/edit" => "grades#edit"
  
  get "/users/:user_id/history" => "user_histories#for_user"
  get "/courses/:course_id/drop" => "courses#dropStudent"
  get "/courses/:course_id/students/:student_id/drop" => "courses#drop"
  get "/courses/:course_id/requestInactive" => "courses#requestInactive"

  resources :users
  resources :students
  resources :instructors
  resources :super_admins
  resources :student_courses

  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    if params[:course_title] || params[:course_number] || params[:course_instructor] || params[:course_description] || params[:course_status]
        @course = Course.where("title = ? OR number = ? OR instructor =? OR description = ? OR status =?", params[:course_title], params[:course_number],params[:course_instructor], params[:course_description], params[:course_status]).order("created_at DESC")
        render 'viewSelectCourse'
    else
      @course =Course.all
      render 'view'
    end
    
  end
  
  
  def viewSelectCourse
    
  end



  def searchCourse
      
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
     @course = Course.find(params[:id])
     render 'show'
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/edit
  def edit
     @course = Course.find(params[:id])
     render 'edit'
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to static_pages_admin_url, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/edit
  # PATCH/PUT /courses/1.json
  def update
    if @course.status.casecmp("inactive").zero?
      @course.requestedInactive = false
    end
    
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to  viewCourse_path, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
  
  def details
    @course =  Course.find(params[:id])
    render 'details'
  end
  
  def enroll
    @course =  Course.find(params[:id])
    redirect_to static_pages_admin_url  #just a random link.
  
  end
  
  def view
    @course = Course.all
    render 'view'
  end
  
  def students
    if logged_in? && (current_user.type == "Admin" || current_user.type == "SuperAdmin" || current_user.type == "Instructor")
      @students_courses = StudentCourse.where("course_id = ?", params[:course_id])
    else
      redirect_to static_pages_home_url
    end
  end
  
  def requestEnrollment
    if logged_in? && (current_user.type == "Student")
      @student_course = StudentCourse.where("course_id = ?", params[:course_id]).where("student_id = ?", current_user.id).first
      
      if @student_course.blank?
        @student_course = StudentCourse.new
        @student_course.student_id = current_user.id
        @student_course.course_id = params[:course_id]
        @student_course.requested = true
        
        if @student_course.save
          flash[:success] = "Enrollment request received"
          redirect_to static_pages_home_url
        elsif
          flash[:error] = "There was an error processing your enrollment request"
          redirect_to static_pages_home_url
        end
      elsif !@student_course.requested
        @student_course.requested = true
          if @student_course.save
            flash[:success] = "Enrollment request received"
            redirect_to static_pages_home_url
          elsif
            flash[:error] = "There was an error processing your enrollment request"
            redirect_to static_pages_home_url
          end
      else
        flash[:error] = "You have already requested enrollment for this course"
        redirect_to static_pages_home_url
      end
    else
      redirect_to static_pages_home_url
      
    end
  end
  
  def dropStudent
    @student_course = StudentCourse.where("course_id = ?", params[:course_id]).where("student_id = ?", current_user.id).first
    
    if !@student_course.blank?
      if @student_course.destroy
        flash[:success] = "You successfully dropped the course"
        redirect_to '/courses'
      end
    end
  end
  
  def drop
    @student_course = StudentCourse.where("course_id = ?", params[:course_id]).where("student_id = ?", params[:student_id]).first
    
    if !@student_course.blank?
      if @student_course.destroy
        flash[:success] = "You successfully dropped the course"
        redirect_to "/courses/#{params[:course_id]}/students/"
      end
    end
  end
  
  def requestInactive
    @course = Course.find(params[:course_id])
    @course.requestedInactive = true
    
    if @course.save
      flash[:success] = "The request was successfully made."
    else
      flash[:danger] = "An error occured while processing the request. Please try again"
    end
    
    redirect_to "/courses"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
       params.require(:course).permit(:number, :title, :description, :instructor, :start_date, :end_date, :status, :material)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/details.html.erb
<h1>course<h1>

app/views/courses/edit.html.erb
<% provide(:title, 'Edit Course') %>
<h1>Edit course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
     
      <%= f.label :number %>
      <%= f.text_field :number %><br />

      <%= f.label :title %>
      <%= f.text_field :title %><br />

      <%= f.label :description %>
      <%= f.text_field :description %><br />
      
      <%= f.label :instructor %>
      <%= f.text_field :instructor %><br />

      <%= f.label :start_date %>
      <%= f.date_field :start_date %><br />

      <%= f.label :end_date %>
      <%= f.date_field :end_date %><br />

      <% if current_user.type == "Admin" || current_user.type == "SuperAdmin"%>

      <%= f.label :status %>
      <%= f.text_field :status %><br />

      <%end%>

      <%= f.submit "Edit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<% provide(:title, 'Add Course') %>
<h1>Add course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
     
      <%= f.label :number %>
      <%= f.text_field :number %><br />

      <%= f.label :title %>
      <%= f.text_field :title %><br />

      <%= f.label :description %>
      <%= f.text_field :description %><br />
      
      <%= f.label :instructor %>
      <%= f.text_field :instructor %><br />

      <%= f.label :start_date %>
      <%= f.date_field :start_date %><br />

      <%= f.label :end_date %>
      <%= f.date_field :end_date %><br />

      <%= f.label :status %>
      <%= f.text_field :status %><br />


      <%= f.submit "Add Course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/searchCourse.html.erb
<% if current_user.type == "Student" %>
    <h3>Apply filters</h3>
    <p>*Fill in at least 1 field</p>
      <%= form_tag(courses_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <ul>
      <%= text_field_tag :course_title, params[:course_title], class: "span2", placeholder: "Course Title" %> 
      </ul>
      <ul>
      <%= text_field_tag :course_number, params[:course_number], class: "span2", placeholder: "Course Number" %>
      </ul>
      <ul>
      <%= text_field_tag :course_instructor, params[:course_instructor], class: "span2", placeholder: "Course Instructer" %>
      </ul>
      <ul>
      <%= text_field_tag :course_description, params[:course_description], class: "span2", placeholder: "Course Description" %>
      </ul>
      <ul>
      <%= text_field_tag :course_status, params[:course_status], class: "span2", placeholder: "Active or Inactive" %>
      </ul>
      
      <button class= "btn" type="submit"><a>Search</a></button>
      
    </div>
    
    
   <%end%>  

    

 <%end%>
 
 
 

app/views/courses/show.html.erb
   
<div class="container">
        <h3>Name</h3>
           <b><%= @course.title %></b>
        <h4>Description</h4>
            <p><%= @course.description %></p>
        <h4>Instructor</h4>
            <p><%= @course.instructor %></p>

 <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" || (current_user.type == "Instructor" &&  @course.instructor == current_user.name)%>
        <p><%= link_to('Edit', controller: 'courses', action:'edit', id: @course.id , class: "btn btn-lg btn-primary")  %> <p>
        <p><%= link_to "Delete", id: @course.id, method: :delete, class: "btn btn-lg btn-primary", data: { confirm: "You sure?" }  %><p>
        <p><%= link_to "View enrolled students", id: @course.id, method: :delete, class: "btn btn-lg btn-primary", data: { confirm: "You sure?" }  %><p>    
        <h3>Course Material</h3>
        <% if @course.material.blank? %>
        <p>No material added</p>
        <%else%>
        <p><%= @course.material %></p><br>
        <%end%>
        
        <%= form_for(@course) do |f| %>
        <%= f.label :material %><br>
        <%= f.text_field :material %><br><br>
        <%= f.submit "Add", class: "btn btn-primary" %>
        <%end%>
        
 <% end %>


<% if current_user.type == "Student"%>

    <h3>Course Material</h3>
        <% if @course.material.blank? %>
        <p>No material added</p>
        <%else%>
        <p><%= @course.material %></p><br>
        <%end%>

<% @student_course = StudentCourse.where("course_id = ?", @course.id).where("student_id = ?", current_user.id).first %>
<% if @student_course.blank? || !@student_course.requested %>
 <p><%= link_to('Request Enrollment',  "#{@course.id}/requestEnrollment" , class: "btn btn-lg btn-primary", data: { confirm: "Are you sure you want to request an enrollment for this course?" }) %> </p>
 <% end %>
        <% end %>
        
</div>

app/views/courses/students.html.erb
<p id="notice"><%= notice %></p>
<% course = Course.find(params[:course_id]) %>
<h1>Students in <%= course.title%></h1>


<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" ||  current_user.type == "Instructor" %>
        <th>Student Name</th>
      <% end %>
      <th>Grade</th>
      <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" ||  current_user.type == "Instructor"%>
        <th>Grade Action</th>
        <th>Drop Action</th>
        <th colspan="4"></th>
      <% else %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @students_courses.each do |student_course| %>
      <tr>
        <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" || current_user.type == "Instructor" %>
          <td><%= Student.find(student_course.student_id).name %></td>
        <% end %>
        <td><%= student_course.grade %></td>
        <% if current_user.type == "Admin"|| current_user.type == "SuperAdmin" || (current_user.type == "Instructor" &&  course.instructor == current_user.name)%>
          <% if student_course.grade.blank? %>
            <td><%= link_to 'Post grade', "/student_courses/#{student_course.id}/edit"  %></td>
          <% else %>
            <td><%= link_to 'Edit grade', "/student_courses/#{student_course.id}/edit"  %></td>
          <% end %>
          <td><%= link_to 'Drop', "/courses/#{student_course.course_id}/students/#{student_course.student_id}/drop", data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<% if current_user.type == "Admin" || current_user.type == "SuperAdmin" || (current_user.type == "Instructor" &&  course.instructor == current_user.name)%>
  <%= link_to 'Post a grade', new_grade_path %>
<% end %>

app/views/courses/view.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Course Number</th>
        <th>Title</th>
        <!--<th>Description</th>-->
        <th>Instructor</th>
        <!--<th>Start Date</th>-->
        <!--<th>End Date</th>-->
        <th>Course Status</th>
        <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" || current_user.type == "Instructor" %>
          <th>Students</th>
        <% end %>
        <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
        <% if current_user.type == "Student" %>
         <th>Enrollment Status</th>
         <th>Action</th>
        <% end %>
      </tr>
    </thead>
    
    <% @course.each do |course|%>
    <% @student_course = StudentCourse.where("student_id = ?", current_user.id).where("course_id = ?", course.id).first %>
    <tbody>
      <tr>
        <td><%= link_to(course.number,course , controller: 'courses' , action: 'show') %></td>
        <td><%= course.title %></td>
        <!--<td><%= course.description %></td>-->
        <td><%= course.instructor %></td>
        <!--<td><%= course.start_date %></td>-->
        <!--<td><%= course.end_date %></td>-->
        <% if current_user.type == "Instructor" && current_user.name == course.instructor && course.status.casecmp("active").zero? && course.requestedInactive == false %>
          <td><%= course.status %> <%= link_to('(Request Inactive)', "/courses/#{course.id}/requestInactive") %></td>
        <% elsif (current_user.type == "SuperAdmin" || current_user.type == "Admin") && course.status.casecmp("active").zero? && course.requestedInactive == true %>
          <td><%= course.status %> (Request received to make inactive) </td>
        <% else %>
          <td><%= course.status %></td>
        <% end %>
        <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" || current_user.type == "Instructor" %>
          <td><%= link_to('View students', "/courses/#{course.id}/students")  %></td>
        <% end %>
        <% if current_user.type == "Admin" || current_user.type == "SuperAdmin" %>
        <td><%= link_to('Edit', controller: 'courses', action:'edit', id: @course.ids)  %> </td>
        <td><%= link_to "Delete", course, method: :delete, data: { confirm: "You sure?" }  %></td>
         <% end %>
        <% if current_user.type == "Student"%>
          <% if !@student_course.nil? %>
            <% if @student_course.enrolled %>
              <td>Enrolled</td>
              <td><%= link_to 'Drop', "courses/#{course.id}/drop", data: { confirm: 'Are you sure?'} %></td>
            <% elsif @student_course.requested %>
              <td>Waiting on approval</td>
              <td>N/A</td>
            <% else %>
             <td>Not Enrolled</td>
             <% if course.status.casecmp("inactive").zero? %>
               <td>Can't enroll, course inactive<td>
             <% else %> 
               <td><%= link_to 'Request enrollment', "courses/#{course.id}/requestEnrollment" %><td>
             <% end %>
          <% end %>
          <% else %>
            <td>Not Enrolled</td>
             <% if course.status.casecmp("inactive").zero? %>
               <td>Can't enroll, course inactive<td>
             <% else %> 
          
               <td><%= link_to 'Request enrollment', "courses/#{course.id}/requestEnrollment" %><td>
             <% end %>
          <% end %>
        <% end %>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/courses/viewSelectCourse.html.erb
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Course Number</th>
        <th>Title</th>
        <th>Instructor</th>
        <th>Status</th>
        <th>Enrollment Status</th>
    
      </tr>
    </thead>
  
  <div class="course">

    <% @course.each do |course| %>
      <% @student_course = StudentCourse.where("student_id = ?", current_user.id).where("course_id = ?", course.id).first %>
      <tr>
        <td><%= link_to(course.number,course , controller: 'courses' , action: 'show') %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.status %></td>
          <% if current_user.type == "Student"%>
          <% if !@student_course.nil? %>
            <% if @student_course.enrolled %>
              <td>Enrolled</td>
            <% elsif @student_course.requested %>
              <td>Waiting on approval</td>
            <% else %>
             <td><%= link_to 'Request enrollment', "courses/#{course.id}/requestEnrollment" %><td>
            <% end %>
          <% else %>
            <td><%= link_to 'Request enrollment', "courses/#{course.id}/requestEnrollment" %><td>
          <% end %>
        <% end %>
        </tr>

  <% end %>
</div>

</table>  

</div>